version: '3.8'
services:
  app:
    image: milansomyk/air_companies_management_system:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/air_companies_management?createIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: mysql:8.2.0
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: air_companies_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: root