version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: air_companies_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - ./volumes/mysql:/ver/lib/mysql
    ports:
      - 5555:3306
    restart: on-failure
  app:
    build:
      context: .
    ports:
      - 8000:8080
    volumes:
      - ./volumes/backend:/app
    restart: on-failure
    command:
      - sh -c "java -jar  app.jar"
    depends_on:
      - db