spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/air_companies_management?createIfNotExist=true
    username: root
    password: root